stages:
  preprocess:
    cmd: python source/preprocess.py
    deps:
    - source/preprocess.py
    - data/raw/
    params:
    - preprocess.buffer_size
    - preprocess.n_fft
    - preprocess.win_length
    - preprocess.hop_length
    - preprocess.audio_dir
    - preprocess.midi_dir
    outs:
    - data/processed/
  train:
    cmd: python source/train.py
    deps:
    - source/train.py
    - source/model.py
    - data/processed/
    params:
    - model.hidden_size_lstm
    - model.hidden_size_linear
    - model.num_lstm_layers
    - model.num_linear_layers
    - train.epochs
    - train.batch_size
    - train.learning_rate
    - train.device_request
    - train.num_eval_batches
    - train.lambda_reg
    - train.max_voices
    outs:
    - models/checkpoints/
#   export:
#     cmd: python source/export.py
#     deps:
#     - source/export.py
#     - models/checkpoints/
#     params:
#     - general.input_size
#     outs:
#     - models/exports/
  save_logs:
    cmd: python source/utils/logs.py
    deps:
    - source/utils/logs.py
    outs:
    - exp_logs/
