general:
  random_seed: 42
  midi_output_dir: 'temp/midi_predictions'

preprocess:
  audio_dir: 'data/raw/debug/separated_jazz_track_stems'  # Directory containing the audio files
  midi_dir: 'data/raw/debug/midi_solos'  # Directory containing the MIDI files
  buffer_size: 128

  ## Parameters for the spectrogram ##
  n_fft: &n_fft 4096  # Size of the FFT window
  win_length: *n_fft  # Window length (can be same as n_fft)
  hop_length: *n_fft  # Hop length equal to n_fft (no overlap)
  
  test_split: 0.2 # Fraction of data to use for testing

model:
  hidden_size: 1500  # Number of hidden units in the RNN
  num_lstm_layers: 1  # Number of LSTM layers in the RNN

train:
  epochs: 200  # Number of epochs to train the model
  batch_size: 128  # Batch size for training
  learning_rate: 0.005  # Learning rate for the optimizer
  device_request: 'cuda'  # Device to use for training (cpu or cuda)
  num_eval_batches: 10  # Number of batches to evaluate on during training
  lambda_reg: 0.0 # Regularization control parameter
  max_voices: 5  # Maximum number of voices to consider in the model